version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"