var machine_3 = {
    "machine": "D-003",
    "frequency": [],
    "Speed": [],
    "Status": [],
    "g_change": [],
    "have_transient": [],
    "pred_avg_detail_1": [],
    "pred_avg_detail_2": [],
    "pred_avg_detail_3": [],
    "pred_avg_detail_4": [],
    "pred_avg_detail_5": [],
    "pred_avg_detail_6": [],
    "pred_avg_detail_7": [],
    "pred_avg_detail_8": [],
    "pred_avg_detail_9": [],
    "pred_avg_detail_10": [],
    "pred_avg_detail_11": [],
    "pred_avg_detail_12": [],
    "pred_avg_detail_13": [],
    "standard_max_detail_1": 0,
    "standard_max_detail_2": 0,
    "standard_max_detail_3": 0,
    "standard_max_detail_4": 0,
    "standard_max_detail_5": 0,
    "standard_max_detail_6": 0,
    "standard_max_detail_7": 0,
    "standard_max_detail_8": 0,
    "standard_max_detail_9": 0,
    "standard_max_detail_10": 0,
    "standard_max_detail_11": 0,
    "standard_max_detail_12": 0,
    "standard_max_detail_13": 0,
    "standard_min_detail_1": 3,
    "standard_min_detail_2": 2,
    "standard_min_detail_3": 6,
    "standard_min_detail_4": 2,
    "standard_min_detail_5": 2,
    "standard_min_detail_6": 3,
    "standard_min_detail_7": 2,
    "standard_min_detail_8": 0,
    "standard_min_detail_9": 0,
    "standard_min_detail_10": 0,
    "standard_min_detail_11": 0,
    "standard_min_detail_12": 0,
    "standard_min_detail_13": 0
}
var machine_5 = {
    "machine": "D-005",
    "frequency": [],
    "Speed": [],
    "Status": [],
    "g_change": [],
    "have_transient": [],
    "pred_avg_detail_1": [],
    "pred_avg_detail_2": [],
    "pred_avg_detail_3": [],
    "pred_avg_detail_4": [],
    "pred_avg_detail_5": [],
    "pred_avg_detail_6": [],
    "pred_avg_detail_7": [],
    "pred_avg_detail_8": [],
    "pred_avg_detail_9": [],
    "pred_avg_detail_10": [],
    "pred_avg_detail_11": [],
    "pred_avg_detail_12": [],
    "pred_avg_detail_13": [],
    "standard_max_detail_1": 0,
    "standard_max_detail_2": 0,
    "standard_max_detail_3": 0,
    "standard_max_detail_4": 0,
    "standard_max_detail_5": 0,
    "standard_max_detail_6": 0,
    "standard_max_detail_7": 0,
    "standard_max_detail_8": 0,
    "standard_max_detail_9": 0,
    "standard_max_detail_10": 0,
    "standard_max_detail_11": 0,
    "standard_max_detail_12": 0,
    "standard_max_detail_13": 0,
    "standard_min_detail_1": 3,
    "standard_min_detail_2": 2,
    "standard_min_detail_3": 6,
    "standard_min_detail_4": 2,
    "standard_min_detail_5": 2,
    "standard_min_detail_6": 3,
    "standard_min_detail_7": 2,
    "standard_min_detail_8": 0,
    "standard_min_detail_9": 0,
    "standard_min_detail_10": 0,
    "standard_min_detail_11": 0,
    "standard_min_detail_12": 0,
    "standard_min_detail_13": 0
}

var api_data = [
    {
        "time": "2023-04-24 17:12:10",
        "machine": "D-005",
        "shift": "白班",
        "frequency": 5.4167,
        "Speed": 321,
        "Status": 2,
        "x_change": 1050.2738,
        "y_change": 1354.9321,
        "z_change": 1346.9975,
        "g_change": 76274.4711,
        "pred_max_detail_1": 3.2886,
        "pred_max_detail_2": 2.2516,
        "pred_max_detail_3": 6.2279,
        "pred_max_detail_4": 2.7069,
        "pred_max_detail_5": 2.2338,
        "pred_max_detail_6": 3.3046,
        "pred_max_detail_7": 2.4583,
        "pred_max_detail_8": 0.4045,
        "pred_max_detail_9": 0.59,
        "pred_max_detail_10": 0.5852,
        "pred_max_detail_11": 0.5768,
        "pred_max_detail_12": 0.5948,
        "pred_max_detail_13": 0.5836,
        "pred_min_detail_1": 3.2708,
        "pred_min_detail_2": 2.2333,
        "pred_min_detail_3": 6.1929,
        "pred_min_detail_4": 2.6931,
        "pred_min_detail_5": 2.22,
        "pred_min_detail_6": 3.287,
        "pred_min_detail_7": 2.4235,
        "pred_min_detail_8": 0.4043,
        "pred_min_detail_9": 0.5606,
        "pred_min_detail_10": 0.5596,
        "pred_min_detail_11": 0.5731,
        "pred_min_detail_12": 0.5746,
        "pred_min_detail_13": 0.5399,
        "have_transient": 1,
        "standard_max_detail_1": 3.35,
        "standard_max_detail_2": 2.3,
        "standard_max_detail_3": 6.3,
        "standard_max_detail_4": 2.77,
        "standard_max_detail_5": 2.3,
        "standard_max_detail_6": 3.37,
        "standard_max_detail_7": 2.54,
        "standard_max_detail_8": 0.42,
        "standard_max_detail_9": 0.63,
        "standard_max_detail_10": 0.63,
        "standard_max_detail_11": 0.63,
        "standard_max_detail_12": 0.63,
        "standard_max_detail_13": 0.63,
        "standard_min_detail_1": 3.25,
        "standard_min_detail_2": 2.2,
        "standard_min_detail_3": 6.14,
        "standard_min_detail_4": 2.63,
        "standard_min_detail_5": 2.1,
        "standard_min_detail_6": 3.23,
        "standard_min_detail_7": 2.34,
        "standard_min_detail_8": 0.38,
        "standard_min_detail_9": 0.53,
        "standard_min_detail_10": 0.53,
        "standard_min_detail_11": 0.53,
        "standard_min_detail_12": 0.53,
        "standard_min_detail_13": 0.53
    },
    {
        "time": "2023-04-24 17:12:10",
        "machine": "D-003",
        "shift": "白班",
        "frequency": 5.4167,
        "Speed": 321,
        "Status": 2,
        "x_change": 1050.2738,
        "y_change": 1354.9321,
        "z_change": 1346.9975,
        "g_change": 76274.4711,
        "pred_max_detail_1": 3.2886,
        "pred_max_detail_2": 2.2516,
        "pred_max_detail_3": 6.2279,
        "pred_max_detail_4": 2.7069,
        "pred_max_detail_5": 2.2338,
        "pred_max_detail_6": 3.3046,
        "pred_max_detail_7": 2.4583,
        "pred_max_detail_8": 0.4045,
        "pred_max_detail_9": 0.59,
        "pred_max_detail_10": 0.5852,
        "pred_max_detail_11": 0.5768,
        "pred_max_detail_12": 0.5948,
        "pred_max_detail_13": 0.5836,
        "pred_min_detail_1": 3.2708,
        "pred_min_detail_2": 2.2333,
        "pred_min_detail_3": 6.1929,
        "pred_min_detail_4": 2.6931,
        "pred_min_detail_5": 2.22,
        "pred_min_detail_6": 3.287,
        "pred_min_detail_7": 2.4235,
        "pred_min_detail_8": 0.4043,
        "pred_min_detail_9": 0.5606,
        "pred_min_detail_10": 0.5596,
        "pred_min_detail_11": 0.5731,
        "pred_min_detail_12": 0.5746,
        "pred_min_detail_13": 0.5399,
        "have_transient": 1,
        "standard_max_detail_1": 3.35,
        "standard_max_detail_2": 2.3,
        "standard_max_detail_3": 6.3,
        "standard_max_detail_4": 2.77,
        "standard_max_detail_5": 2.3,
        "standard_max_detail_6": 3.37,
        "standard_max_detail_7": 2.54,
        "standard_max_detail_8": 0.42,
        "standard_max_detail_9": 0.63,
        "standard_max_detail_10": 0.63,
        "standard_max_detail_11": 0.63,
        "standard_max_detail_12": 0.63,
        "standard_max_detail_13": 0.63,
        "standard_min_detail_1": 3.25,
        "standard_min_detail_2": 2.2,
        "standard_min_detail_3": 6.14,
        "standard_min_detail_4": 2.63,
        "standard_min_detail_5": 2.1,
        "standard_min_detail_6": 3.23,
        "standard_min_detail_7": 2.34,
        "standard_min_detail_8": 0.38,
        "standard_min_detail_9": 0.53,
        "standard_min_detail_10": 0.53,
        "standard_min_detail_11": 0.53,
        "standard_min_detail_12": 0.53,
        "standard_min_detail_13": 0.53
    }
]

var machines = {
    "D-005": machine_5,
    "D-003": machine_3,
    
}

setInterval(() => {
    // 從陣列中獲取資料
    for (let i = 0; i < api_data.length; i++) {
        let json = api_data[i];
        console.log(machines[json.machine].frequency)
        if (machines[json.machine].Status.length > 100) {
            Object.keys(machines[json.machine]).forEach(key => {
                if (Array.isArray(machines[json.machine][key])) {
                    machines[json.machine][key].shift();
                }
              });
        }

        machines[json.machine].frequency.push(json.frequency);
        machines[json.machine].Speed.push(json.Speed);
        machines[json.machine].Status.push(json.Status);
        machines[json.machine].g_change.push(json.g_change);
        for (let i = 1; i <= 13; i++) {
            let detailName = `detail_${i}`;
            machines[json.machine][`pred_avg_${detailName}`].push((json[`standard_max_${detailName}`]+json[`standard_min_${detailName}`])/2);
            machines[json.machine][`standard_max_${detailName}`] = json[`standard_max_${detailName}`];
            machines[json.machine][`standard_min_${detailName}`] = json[`standard_min_${detailName}`];      
      }
    }
}, 1000);